version: "3"
services:
  tindev-api-db:
    container_name: tindev-api-mongo
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./mongodb_data:/bitnami
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
